//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace allpax_sale_miner.Models
{
    public partial class tbl_eqpmt_kits_avlbl
    {
        public string eqpmtType { get; set; }
        public string kitID { get; set; }
        public int id { get; set; }
    }
}
